export const USER_GEOLOCATION_FETCH_REQUESTED = '@@user/USER_GEOLOCATION_FETCH_REQUESTED';
export const USER_GEOLOCATION_FETCH_SUCCEEDED = '@@user/USER_GEOLOCATION_FETCH_SUCCEEDED';
export const USER_GEOLOCATION_FETCH_FAILED = '@@user/USER_GEOLOCATION_FETCH_FAILED';
